"""add player contract state snapshot and wage config tables

Revision ID: 2081433544b6
Revises: c4d2e8f91a6b
Create Date: 2026-05-28 18:03:57.684851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2081433544b6'
down_revision: Union[str, Sequence[str], None] = 'c4d2e8f91a6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wage_configs',
    sa.Column('config_type', sa.Enum('BASE_WAGE', 'LEAGUE_FACTOR', 'AGE_FACTOR', 'CONTRACT_TYPE_FACTOR', 'ROLE_FACTOR', name='wageconfigtype'), nullable=False),
    sa.Column('level_key', sa.String(length=50), nullable=False),
    sa.Column('value', sa.DECIMAL(precision=10, scale=4), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('config_type', 'level_key', name='uix_wage_config_type_level')
    )
    op.create_index(op.f('ix_wage_configs_config_type'), 'wage_configs', ['config_type'], unique=False)
    op.create_table('player_contracts',
    sa.Column('player_id', sa.String(length=36), nullable=False),
    sa.Column('team_id', sa.String(length=36), nullable=True),
    sa.Column('season_id', sa.String(length=36), nullable=True),
    sa.Column('contract_type', sa.Enum('NORMAL', 'ROOKIE', 'FREE', name='contracttype'), nullable=False),
    sa.Column('start_season_number', sa.Integer(), nullable=False),
    sa.Column('end_season_number', sa.Integer(), nullable=True),
    sa.Column('wage', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('recommended_wage', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('wage_ratio', sa.DECIMAL(precision=5, scale=2), nullable=False),
    sa.Column('wage_satisfaction', sa.Integer(), nullable=False),
    sa.Column('release_clause', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('squad_role', sa.Enum('KEY_PLAYER', 'FIRST_TEAM', 'ROTATION', 'BACKUP', 'HOT_PROSPECT', 'YOUNGSTER', 'NOT_NEEDED', name='squadrole'), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_player_contracts_player_id'), 'player_contracts', ['player_id'], unique=False)
    op.create_index(op.f('ix_player_contracts_team_id'), 'player_contracts', ['team_id'], unique=False)
    op.create_table('player_state_snapshots',
    sa.Column('player_id', sa.String(length=36), nullable=False),
    sa.Column('team_id', sa.String(length=36), nullable=True),
    sa.Column('season_id', sa.String(length=36), nullable=True),
    sa.Column('source_event', sa.String(length=50), nullable=False),
    sa.Column('contract_score', sa.Integer(), nullable=False),
    sa.Column('recent_match_score', sa.Integer(), nullable=False),
    sa.Column('fitness_score', sa.Integer(), nullable=False),
    sa.Column('match_load_score', sa.Integer(), nullable=False),
    sa.Column('match_rust_score', sa.Integer(), nullable=False),
    sa.Column('training_load_score', sa.Integer(), nullable=False),
    sa.Column('morale_score', sa.Integer(), nullable=False),
    sa.Column('total_score', sa.Integer(), nullable=False),
    sa.Column('visible_form', sa.Enum('HOT', 'GOOD', 'NEUTRAL', 'LOW', name='matchform'), nullable=False),
    sa.Column('attribute_modifier_pct', sa.DECIMAL(precision=6, scale=4), nullable=False),
    sa.Column('stamina_modifier', sa.DECIMAL(precision=6, scale=2), nullable=False),
    sa.Column('meta_data', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_player_state_snapshots_player_id'), 'player_state_snapshots', ['player_id'], unique=False)
    op.add_column('players', sa.Column('recommended_wage', sa.DECIMAL(precision=12, scale=2), nullable=True))
    op.add_column('players', sa.Column('wage_ratio', sa.DECIMAL(precision=5, scale=2), nullable=True))
    op.add_column('players', sa.Column('wage_satisfaction', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('players', sa.Column('state_score', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('players', sa.Column('state_updated_at', sa.DateTime(), nullable=True))
    op.add_column('players', sa.Column('match_rust_score', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'match_rust_score')
    op.drop_column('players', 'state_updated_at')
    op.drop_column('players', 'state_score')
    op.drop_column('players', 'wage_satisfaction')
    op.drop_column('players', 'wage_ratio')
    op.drop_column('players', 'recommended_wage')
    op.drop_index(op.f('ix_player_state_snapshots_player_id'), table_name='player_state_snapshots')
    op.drop_table('player_state_snapshots')
    op.drop_index(op.f('ix_player_contracts_team_id'), table_name='player_contracts')
    op.drop_index(op.f('ix_player_contracts_player_id'), table_name='player_contracts')
    op.drop_table('player_contracts')
    op.drop_index(op.f('ix_wage_configs_config_type'), table_name='wage_configs')
    op.drop_table('wage_configs')
    # ### end Alembic commands ###
