"""add_player_detailed_stats

Revision ID: 214e9a5954e4
Revises: cbde578eaaa0
Create Date: 2026-06-05 19:45:44.660671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '214e9a5954e4'
down_revision: Union[str, Sequence[str], None] = 'cbde578eaaa0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    columns = [
        'shots', 'shots_on_target', 'dribbles', 'dribbles_succ',
        'headers', 'headers_succ', 'passes', 'passes_succ', 'key_passes',
        'crosses', 'crosses_succ', 'tackles', 'tackles_succ',
        'interceptions', 'clearances', 'blocks', 'saves',
        'fouls', 'fouls_drawn', 'offsides', 'turnovers', 'touches',
        'free_kicks', 'free_kick_goals', 'penalties', 'penalty_goals',
    ]
    for col in columns:
        op.add_column('player_season_stats', sa.Column(col, sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player_season_stats', 'penalty_goals')
    op.drop_column('player_season_stats', 'penalties')
    op.drop_column('player_season_stats', 'free_kick_goals')
    op.drop_column('player_season_stats', 'free_kicks')
    op.drop_column('player_season_stats', 'touches')
    op.drop_column('player_season_stats', 'turnovers')
    op.drop_column('player_season_stats', 'offsides')
    op.drop_column('player_season_stats', 'fouls_drawn')
    op.drop_column('player_season_stats', 'fouls')
    op.drop_column('player_season_stats', 'saves')
    op.drop_column('player_season_stats', 'blocks')
    op.drop_column('player_season_stats', 'clearances')
    op.drop_column('player_season_stats', 'interceptions')
    op.drop_column('player_season_stats', 'tackles_succ')
    op.drop_column('player_season_stats', 'tackles')
    op.drop_column('player_season_stats', 'crosses_succ')
    op.drop_column('player_season_stats', 'crosses')
    op.drop_column('player_season_stats', 'key_passes')
    op.drop_column('player_season_stats', 'passes_succ')
    op.drop_column('player_season_stats', 'passes')
    op.drop_column('player_season_stats', 'headers_succ')
    op.drop_column('player_season_stats', 'headers')
    op.drop_column('player_season_stats', 'dribbles_succ')
    op.drop_column('player_season_stats', 'dribbles')
    op.drop_column('player_season_stats', 'shots_on_target')
    op.drop_column('player_season_stats', 'shots')
    # ### end Alembic commands ###
