"""add_team_honors_table

Revision ID: 30deaf0048f7
Revises: 3a8f2e1b4c5d
Create Date: 2026-06-10 00:28:37.127615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30deaf0048f7'
down_revision: Union[str, Sequence[str], None] = '3a8f2e1b4c5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team_honors',
    sa.Column('team_id', sa.String(length=36), nullable=False),
    sa.Column('season_id', sa.String(length=36), nullable=False),
    sa.Column('honor_type', sa.Enum('LEAGUE_CHAMPION', 'CUP_CHAMPION', name='honortype'), nullable=False),
    sa.Column('competition_id', sa.String(length=36), nullable=True),
    sa.Column('competition_name', sa.String(length=50), nullable=True),
    sa.Column('competition_level', sa.Integer(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_team_honors_honor_type'), 'team_honors', ['honor_type'], unique=False)
    op.create_index(op.f('ix_team_honors_season_id'), 'team_honors', ['season_id'], unique=False)
    op.create_index(op.f('ix_team_honors_team_id'), 'team_honors', ['team_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_team_honors_team_id'), table_name='team_honors')
    op.drop_index(op.f('ix_team_honors_season_id'), table_name='team_honors')
    op.drop_index(op.f('ix_team_honors_honor_type'), table_name='team_honors')
    op.drop_table('team_honors')
    # ### end Alembic commands ###
