"""remove_ovr_column

Revision ID: 58f5f5484083
Revises: 
Create Date: 2026-05-02 05:22:18.927513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58f5f5484083'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('league_systems',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('zone_id', sa.Integer(), nullable=False),
    sa.Column('max_teams_per_league', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_league_systems_zone_id'), 'league_systems', ['zone_id'], unique=False)
    op.create_table('seasons',
    sa.Column('season_number', sa.Integer(), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'ONGOING', 'FINISHED', name='seasonstatus'), nullable=False),
    sa.Column('current_day', sa.Integer(), nullable=False),
    sa.Column('current_league_round', sa.Integer(), nullable=False),
    sa.Column('current_cup_round', sa.Integer(), nullable=False),
    sa.Column('total_days', sa.Integer(), nullable=False),
    sa.Column('league_days', sa.Integer(), nullable=False),
    sa.Column('cup_start_day', sa.Integer(), nullable=False),
    sa.Column('cup_interval', sa.Integer(), nullable=False),
    sa.Column('offseason_start', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('season_number', 'zone_id', name='uix_season_number_zone')
    )
    op.create_index(op.f('ix_seasons_season_number'), 'seasons', ['season_number'], unique=False)
    op.create_index(op.f('ix_seasons_status'), 'seasons', ['status'], unique=False)
    op.create_index(op.f('ix_seasons_zone_id'), 'seasons', ['zone_id'], unique=False)
    op.create_table('users',
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('nickname', sa.String(length=50), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('is_ai', sa.Boolean(), nullable=False),
    sa.Column('is_vip', sa.Boolean(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('experience', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'BANNED', name='userstatus'), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_is_ai'), 'users', ['is_ai'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('leagues',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('system_id', sa.String(length=36), nullable=False),
    sa.Column('max_teams', sa.Integer(), nullable=False),
    sa.Column('promotion_spots', sa.Integer(), nullable=False),
    sa.Column('relegation_spots', sa.Integer(), nullable=False),
    sa.Column('has_promotion_playoff', sa.Boolean(), nullable=False),
    sa.Column('has_relegation_playoff', sa.Boolean(), nullable=False),
    sa.Column('parent_league_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parent_league_id'], ['leagues.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['system_id'], ['league_systems.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leagues_level'), 'leagues', ['level'], unique=False)
    op.create_index(op.f('ix_leagues_parent_league_id'), 'leagues', ['parent_league_id'], unique=False)
    op.create_index(op.f('ix_leagues_system_id'), 'leagues', ['system_id'], unique=False)
    op.create_table('teams',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('short_name', sa.String(length=10), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('stadium', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=50), nullable=True),
    sa.Column('founded_year', sa.Integer(), nullable=True),
    sa.Column('overall_rating', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'SUSPENDED', name='teamstatus'), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('current_league_id', sa.String(length=36), nullable=True),
    sa.Column('current_season_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['current_league_id'], ['leagues.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['current_season_id'], ['seasons.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_teams_current_league_id'), 'teams', ['current_league_id'], unique=False)
    op.create_table('cup_competitions',
    sa.Column('season_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('eligible_league_levels', sa.JSON(), nullable=False),
    sa.Column('total_teams', sa.Integer(), nullable=False),
    sa.Column('has_group_stage', sa.Boolean(), nullable=False),
    sa.Column('group_count', sa.Integer(), nullable=False),
    sa.Column('teams_per_group', sa.Integer(), nullable=False),
    sa.Column('group_rounds', sa.Integer(), nullable=False),
    sa.Column('current_round', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ONGOING', 'FINISHED', name='seasonstatus'), nullable=False),
    sa.Column('winner_team_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['winner_team_id'], ['teams.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cup_competitions_season_id'), 'cup_competitions', ['season_id'], unique=False)
    op.create_table('league_standings',
    sa.Column('league_id', sa.String(length=36), nullable=False),
    sa.Column('season_id', sa.String(length=36), nullable=False),
    sa.Column('team_id', sa.String(length=36), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('played', sa.Integer(), nullable=False),
    sa.Column('won', sa.Integer(), nullable=False),
    sa.Column('drawn', sa.Integer(), nullable=False),
    sa.Column('lost', sa.Integer(), nullable=False),
    sa.Column('goals_for', sa.Integer(), nullable=False),
    sa.Column('goals_against', sa.Integer(), nullable=False),
    sa.Column('goal_difference', sa.Integer(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('form', sa.String(length=10), nullable=True),
    sa.Column('is_promotion_zone', sa.Boolean(), nullable=False),
    sa.Column('is_relegation_zone', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('season_id', 'team_id', name='uix_season_team')
    )
    op.create_index(op.f('ix_league_standings_league_id'), 'league_standings', ['league_id'], unique=False)
    op.create_index(op.f('ix_league_standings_position'), 'league_standings', ['position'], unique=False)
    op.create_index(op.f('ix_league_standings_season_id'), 'league_standings', ['season_id'], unique=False)
    op.create_table('players',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('race', sa.Enum('ASIAN', 'WESTERN', name='playerrace'), nullable=False),
    sa.Column('avatar_url', sa.String(length=200), nullable=True),
    sa.Column('position', sa.Enum('FW', 'MF', 'DF', 'GK', name='playerposition'), nullable=False),
    sa.Column('preferred_foot', sa.Enum('LEFT', 'RIGHT', 'BOTH', name='playerfoot'), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('birth_offset', sa.Integer(), nullable=False),
    sa.Column('sho', sa.Integer(), nullable=False),
    sa.Column('pas', sa.Integer(), nullable=False),
    sa.Column('dri', sa.Integer(), nullable=False),
    sa.Column('spd', sa.Integer(), nullable=False),
    sa.Column('str', sa.Integer(), nullable=False),
    sa.Column('sta', sa.Integer(), nullable=False),
    sa.Column('acc', sa.Integer(), nullable=False),
    sa.Column('hea', sa.Integer(), nullable=False),
    sa.Column('bal', sa.Integer(), nullable=False),
    sa.Column('defe', sa.Integer(), nullable=False),
    sa.Column('tkl', sa.Integer(), nullable=False),
    sa.Column('vis', sa.Integer(), nullable=False),
    sa.Column('cro', sa.Integer(), nullable=False),
    sa.Column('con', sa.Integer(), nullable=False),
    sa.Column('fin', sa.Integer(), nullable=False),
    sa.Column('com', sa.Integer(), nullable=False),
    sa.Column('sav', sa.Integer(), nullable=False),
    sa.Column('ref', sa.Integer(), nullable=False),
    sa.Column('pos', sa.Integer(), nullable=False),
    sa.Column('potential_max', sa.Integer(), nullable=False),
    sa.Column('potential_letter', sa.Enum('S', 'A', 'B', 'C', 'D', name='potentialletter'), nullable=False),
    sa.Column('skills', sa.JSON(), nullable=False),
    sa.Column('personality', sa.Enum('MATERIALISTIC', 'AMBITIOUS', 'PROFESSIONAL', 'PASSIONATE', 'LOYAL', 'TEAM_ORIENTED', name='playerpersonality'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INJURED', 'SUSPENDED', 'RETIRED', name='playerstatus'), nullable=False),
    sa.Column('match_form', sa.Enum('HOT', 'GOOD', 'NEUTRAL', 'LOW', name='matchform'), nullable=False),
    sa.Column('fitness', sa.Integer(), nullable=False),
    sa.Column('contract_type', sa.Enum('NORMAL', 'ROOKIE', 'FREE', name='contracttype'), nullable=False),
    sa.Column('contract_end_season', sa.Integer(), nullable=True),
    sa.Column('wage', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('release_clause', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('squad_role', sa.Enum('KEY_PLAYER', 'FIRST_TEAM', 'ROTATION', 'BACKUP', 'HOT_PROSPECT', 'YOUNGSTER', 'NOT_NEEDED', name='squadrole'), nullable=False),
    sa.Column('market_value', sa.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('matches_played', sa.Integer(), nullable=False),
    sa.Column('goals', sa.Integer(), nullable=False),
    sa.Column('assists', sa.Integer(), nullable=False),
    sa.Column('yellow_cards', sa.Integer(), nullable=False),
    sa.Column('red_cards', sa.Integer(), nullable=False),
    sa.Column('average_rating', sa.DECIMAL(precision=3, scale=1), nullable=False),
    sa.Column('minutes_played', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_players_name'), 'players', ['name'], unique=False)
    op.create_index(op.f('ix_players_position'), 'players', ['position'], unique=False)
    op.create_index(op.f('ix_players_team_id'), 'players', ['team_id'], unique=False)
    op.create_table('team_finances',
    sa.Column('team_id', sa.String(length=36), nullable=False),
    sa.Column('balance', sa.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('weekly_wage_bill', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('stadium_capacity', sa.Integer(), nullable=False),
    sa.Column('ticket_price', sa.DECIMAL(precision=8, scale=2), nullable=False),
    sa.Column('weekly_sponsor_income', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('weekly_ticket_income', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('transfer_budget', sa.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('wage_budget', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('team_id', 'id')
    )
    op.create_table('cup_groups',
    sa.Column('competition_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=10), nullable=False),
    sa.Column('team_ids', sa.JSON(), nullable=False),
    sa.Column('standings', sa.JSON(), nullable=True),
    sa.Column('qualified_team_ids', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['competition_id'], ['cup_competitions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cup_groups_competition_id'), 'cup_groups', ['competition_id'], unique=False)
    op.create_table('fixtures',
    sa.Column('season_id', sa.String(length=36), nullable=False),
    sa.Column('fixture_type', sa.Enum('LEAGUE', 'CUP_LIGHTNING_GROUP', 'CUP_LIGHTNING_KNOCKOUT', 'CUP_JENNY', 'PLAYOFF', name='fixturetype'), nullable=False),
    sa.Column('season_day', sa.Integer(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(), nullable=False),
    sa.Column('round_number', sa.Integer(), nullable=False),
    sa.Column('league_id', sa.String(length=36), nullable=True),
    sa.Column('cup_competition_id', sa.String(length=36), nullable=True),
    sa.Column('cup_group_name', sa.String(length=10), nullable=True),
    sa.Column('cup_stage', sa.String(length=20), nullable=True),
    sa.Column('home_team_id', sa.String(length=36), nullable=False),
    sa.Column('away_team_id', sa.String(length=36), nullable=False),
    sa.Column('home_score', sa.Integer(), nullable=True),
    sa.Column('away_score', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('SCHEDULED', 'ONGOING', 'FINISHED', name='fixturestatus'), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['away_team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['cup_competition_id'], ['cup_competitions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['home_team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fixtures_away_team_id'), 'fixtures', ['away_team_id'], unique=False)
    op.create_index(op.f('ix_fixtures_cup_competition_id'), 'fixtures', ['cup_competition_id'], unique=False)
    op.create_index(op.f('ix_fixtures_fixture_type'), 'fixtures', ['fixture_type'], unique=False)
    op.create_index(op.f('ix_fixtures_home_team_id'), 'fixtures', ['home_team_id'], unique=False)
    op.create_index(op.f('ix_fixtures_league_id'), 'fixtures', ['league_id'], unique=False)
    op.create_index(op.f('ix_fixtures_scheduled_at'), 'fixtures', ['scheduled_at'], unique=False)
    op.create_index(op.f('ix_fixtures_season_day'), 'fixtures', ['season_day'], unique=False)
    op.create_index(op.f('ix_fixtures_season_id'), 'fixtures', ['season_id'], unique=False)
    op.create_index(op.f('ix_fixtures_status'), 'fixtures', ['status'], unique=False)
    op.create_table('player_season_stats',
    sa.Column('player_id', sa.String(length=36), nullable=False),
    sa.Column('season_id', sa.String(length=36), nullable=False),
    sa.Column('team_id', sa.String(length=36), nullable=True),
    sa.Column('league_id', sa.String(length=36), nullable=True),
    sa.Column('cup_competition_id', sa.String(length=36), nullable=True),
    sa.Column('matches_played', sa.Integer(), nullable=False),
    sa.Column('minutes_played', sa.Integer(), nullable=False),
    sa.Column('goals', sa.Integer(), nullable=False),
    sa.Column('assists', sa.Integer(), nullable=False),
    sa.Column('yellow_cards', sa.Integer(), nullable=False),
    sa.Column('red_cards', sa.Integer(), nullable=False),
    sa.Column('clean_sheets', sa.Integer(), nullable=False),
    sa.Column('average_rating', sa.DECIMAL(precision=3, scale=1), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cup_competition_id'], ['cup_competitions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'season_id', 'league_id', 'cup_competition_id', name='uix_player_season_competition')
    )
    op.create_index(op.f('ix_player_season_stats_cup_competition_id'), 'player_season_stats', ['cup_competition_id'], unique=False)
    op.create_index(op.f('ix_player_season_stats_league_id'), 'player_season_stats', ['league_id'], unique=False)
    op.create_index(op.f('ix_player_season_stats_player_id'), 'player_season_stats', ['player_id'], unique=False)
    op.create_index(op.f('ix_player_season_stats_season_id'), 'player_season_stats', ['season_id'], unique=False)
    op.create_index(op.f('ix_player_season_stats_team_id'), 'player_season_stats', ['team_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_player_season_stats_team_id'), table_name='player_season_stats')
    op.drop_index(op.f('ix_player_season_stats_season_id'), table_name='player_season_stats')
    op.drop_index(op.f('ix_player_season_stats_player_id'), table_name='player_season_stats')
    op.drop_index(op.f('ix_player_season_stats_league_id'), table_name='player_season_stats')
    op.drop_index(op.f('ix_player_season_stats_cup_competition_id'), table_name='player_season_stats')
    op.drop_table('player_season_stats')
    op.drop_index(op.f('ix_fixtures_status'), table_name='fixtures')
    op.drop_index(op.f('ix_fixtures_season_id'), table_name='fixtures')
    op.drop_index(op.f('ix_fixtures_season_day'), table_name='fixtures')
    op.drop_index(op.f('ix_fixtures_scheduled_at'), table_name='fixtures')
    op.drop_index(op.f('ix_fixtures_league_id'), table_name='fixtures')
    op.drop_index(op.f('ix_fixtures_home_team_id'), table_name='fixtures')
    op.drop_index(op.f('ix_fixtures_fixture_type'), table_name='fixtures')
    op.drop_index(op.f('ix_fixtures_cup_competition_id'), table_name='fixtures')
    op.drop_index(op.f('ix_fixtures_away_team_id'), table_name='fixtures')
    op.drop_table('fixtures')
    op.drop_index(op.f('ix_cup_groups_competition_id'), table_name='cup_groups')
    op.drop_table('cup_groups')
    op.drop_table('team_finances')
    op.drop_index(op.f('ix_players_team_id'), table_name='players')
    op.drop_index(op.f('ix_players_position'), table_name='players')
    op.drop_index(op.f('ix_players_name'), table_name='players')
    op.drop_table('players')
    op.drop_index(op.f('ix_league_standings_season_id'), table_name='league_standings')
    op.drop_index(op.f('ix_league_standings_position'), table_name='league_standings')
    op.drop_index(op.f('ix_league_standings_league_id'), table_name='league_standings')
    op.drop_table('league_standings')
    op.drop_index(op.f('ix_cup_competitions_season_id'), table_name='cup_competitions')
    op.drop_table('cup_competitions')
    op.drop_index(op.f('ix_teams_current_league_id'), table_name='teams')
    op.drop_table('teams')
    op.drop_index(op.f('ix_leagues_system_id'), table_name='leagues')
    op.drop_index(op.f('ix_leagues_parent_league_id'), table_name='leagues')
    op.drop_index(op.f('ix_leagues_level'), table_name='leagues')
    op.drop_table('leagues')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_is_ai'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_seasons_zone_id'), table_name='seasons')
    op.drop_index(op.f('ix_seasons_status'), table_name='seasons')
    op.drop_index(op.f('ix_seasons_season_number'), table_name='seasons')
    op.drop_table('seasons')
    op.drop_index(op.f('ix_league_systems_zone_id'), table_name='league_systems')
    op.drop_table('league_systems')
    # ### end Alembic commands ###
