"""add_player_number_system

Revision ID: 62b4d4534265
Revises: 71ed170b3b68
Create Date: 2026-06-04 19:17:55.602520

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62b4d4534265'
down_revision: Union[str, Sequence[str], None] = '71ed170b3b68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('preferred_number', sa.Integer(), nullable=True))
    op.add_column('players', sa.Column('squad_number', sa.Integer(), nullable=True))
    # ### end Alembic commands ###

    # Backfill preferred_number based on position
    op.execute("""
        UPDATE players
        SET preferred_number = CASE
            WHEN position = 'FW' THEN 10
            WHEN position = 'MF' THEN 8
            WHEN position = 'DF' THEN 4
            WHEN position = 'GK' THEN 1
            ELSE 10
        END
    """)

    # Make preferred_number non-nullable
    op.alter_column('players', 'preferred_number', existing_type=sa.Integer(), nullable=False)

    # Backfill squad_number for players currently in a team
    connection = op.get_bind()
    result = connection.execute(sa.text("""
        SELECT team_id, position, id, preferred_number
        FROM players
        WHERE team_id IS NOT NULL
        ORDER BY team_id, id
    """))

    team_numbers = {}
    for row in result:
        team_id, position, player_id, preferred = row
        used = team_numbers.setdefault(team_id, set())
        if preferred not in used:
            number = preferred
        else:
            number = None
            for n in range(12, 36):
                if n not in used:
                    number = n
                    break
            if number is None:
                number = preferred
        used.add(number)
        connection.execute(
            sa.text("UPDATE players SET squad_number = :num WHERE id = :pid"),
            {"num": number, "pid": player_id}
        )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'squad_number')
    op.drop_column('players', 'preferred_number')
    # ### end Alembic commands ###
