"""add attribute_progress to training_results

Revision ID: 6868de019995
Revises: bfcccf8c00dc
Create Date: 2026-06-18 19:04:29.066704

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6868de019995'
down_revision: Union[str, Sequence[str], None] = 'bfcccf8c00dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('training_results', sa.Column('attribute_progress', sa.JSON(), nullable=True))
    op.execute("UPDATE training_results SET attribute_progress = '{}' WHERE attribute_progress IS NULL")
    op.alter_column('training_results', 'attribute_progress', existing_type=sa.JSON(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('training_results', 'attribute_progress')
    # ### end Alembic commands ###
