"""add_contract_youth_closed_loop_tables

Revision ID: 84dbdd46a448
Revises: 2081433544b6
Create Date: 2026-05-29 16:14:55.675065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84dbdd46a448'
down_revision: Union[str, Sequence[str], None] = '2081433544b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('draft_pools',
    sa.Column('season_id', sa.String(length=36), nullable=False),
    sa.Column('league_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('PREPARING', 'PREFERENCES_OPEN', 'COMPLETED', name='draftpoolstatus'), nullable=False),
    sa.Column('opened_at_day', sa.Integer(), nullable=False),
    sa.Column('draft_day', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('season_id', 'league_id', name='uix_draft_pool_season_league')
    )
    op.create_index(op.f('ix_draft_pools_league_id'), 'draft_pools', ['league_id'], unique=False)
    op.create_index(op.f('ix_draft_pools_season_id'), 'draft_pools', ['season_id'], unique=False)
    op.create_table('draft_pool_players',
    sa.Column('draft_pool_id', sa.String(length=36), nullable=False),
    sa.Column('player_id', sa.String(length=36), nullable=False),
    sa.Column('source_team_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.Enum('AVAILABLE', 'SELECTED', 'FREE_MARKET', name='draftpoolplayerstatus'), nullable=False),
    sa.Column('selected_by_team_id', sa.String(length=36), nullable=True),
    sa.Column('rank_snapshot', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['draft_pool_id'], ['draft_pools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['selected_by_team_id'], ['teams.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_team_id'], ['teams.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_draft_pool_players_draft_pool_id'), 'draft_pool_players', ['draft_pool_id'], unique=False)
    op.create_index(op.f('ix_draft_pool_players_player_id'), 'draft_pool_players', ['player_id'], unique=False)
    op.create_table('draft_preferences',
    sa.Column('draft_pool_id', sa.String(length=36), nullable=False),
    sa.Column('team_id', sa.String(length=36), nullable=False),
    sa.Column('player_id', sa.String(length=36), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('excluded', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['draft_pool_id'], ['draft_pools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('draft_pool_id', 'team_id', 'player_id', name='uix_draft_preference')
    )
    op.create_index(op.f('ix_draft_preferences_draft_pool_id'), 'draft_preferences', ['draft_pool_id'], unique=False)
    op.create_index(op.f('ix_draft_preferences_team_id'), 'draft_preferences', ['team_id'], unique=False)
    op.create_table('draft_selections',
    sa.Column('draft_pool_id', sa.String(length=36), nullable=False),
    sa.Column('team_id', sa.String(length=36), nullable=False),
    sa.Column('player_id', sa.String(length=36), nullable=False),
    sa.Column('season_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SIGNED', 'DECLINED', 'EXPIRED', 'SKIPPED_ROSTER_FULL', name='draftselectionstatus'), nullable=False),
    sa.Column('selection_order', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['draft_pool_id'], ['draft_pools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('draft_pool_id', 'team_id', name='uix_draft_selection_team')
    )
    op.create_index(op.f('ix_draft_selections_draft_pool_id'), 'draft_selections', ['draft_pool_id'], unique=False)
    op.create_index(op.f('ix_draft_selections_status'), 'draft_selections', ['status'], unique=False)
    op.create_index(op.f('ix_draft_selections_team_id'), 'draft_selections', ['team_id'], unique=False)
    op.create_table('free_agent_listings',
    sa.Column('player_id', sa.String(length=36), nullable=False),
    sa.Column('league_id', sa.String(length=36), nullable=True),
    sa.Column('season_id', sa.String(length=36), nullable=False),
    sa.Column('origin', sa.Enum('CONTRACT_EXPIRED', 'RELEASED', 'DRAFT_UNSELECTED', 'DRAFT_DECLINED', 'AUTO_GENERATED', name='freeagentorigin'), nullable=False),
    sa.Column('signing_fee', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('recommended_wage', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('listed_at_day', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'SIGNED', 'EXPIRED', 'RETIRED', name='listingstatus'), nullable=False),
    sa.Column('signed_team_id', sa.String(length=36), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['signed_team_id'], ['teams.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_free_agent_listings_league_id'), 'free_agent_listings', ['league_id'], unique=False)
    op.create_index('ix_free_agent_listings_player_active', 'free_agent_listings', ['player_id', 'status'], unique=False)
    op.create_index(op.f('ix_free_agent_listings_player_id'), 'free_agent_listings', ['player_id'], unique=False)
    op.create_index(op.f('ix_free_agent_listings_season_id'), 'free_agent_listings', ['season_id'], unique=False)
    op.create_index(op.f('ix_free_agent_listings_signed_team_id'), 'free_agent_listings', ['signed_team_id'], unique=False)
    op.create_index(op.f('ix_free_agent_listings_status'), 'free_agent_listings', ['status'], unique=False)
    op.create_index('ix_free_agent_listings_status_season', 'free_agent_listings', ['status', 'season_id'], unique=False)
    op.create_table('youth_academy_players',
    sa.Column('player_id', sa.String(length=36), nullable=False),
    sa.Column('team_id', sa.String(length=36), nullable=False),
    sa.Column('season_id', sa.String(length=36), nullable=False),
    sa.Column('joined_season_number', sa.Integer(), nullable=False),
    sa.Column('joined_day', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('IN_ACADEMY', 'SIGNED', 'RELEASED_TO_DRAFT', 'DRAFTED', 'FREE_MARKET', name='academyplayerstatus'), nullable=False),
    sa.Column('growth_speed', sa.Enum('FAST', 'NORMAL', 'SLOW', name='growthspeed'), nullable=False),
    sa.Column('growth_score', sa.DECIMAL(precision=5, scale=2), nullable=False),
    sa.Column('last_trained_day', sa.Integer(), nullable=True),
    sa.Column('signed_at_season', sa.Integer(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_youth_academy_players_player_id'), 'youth_academy_players', ['player_id'], unique=True)
    op.create_index(op.f('ix_youth_academy_players_season_id'), 'youth_academy_players', ['season_id'], unique=False)
    op.create_index(op.f('ix_youth_academy_players_status'), 'youth_academy_players', ['status'], unique=False)
    op.create_index(op.f('ix_youth_academy_players_team_id'), 'youth_academy_players', ['team_id'], unique=False)
    op.create_table('youth_academy_snapshots',
    sa.Column('academy_player_id', sa.String(length=36), nullable=False),
    sa.Column('season_id', sa.String(length=36), nullable=False),
    sa.Column('season_day', sa.Integer(), nullable=False),
    sa.Column('ovr', sa.Integer(), nullable=False),
    sa.Column('attributes', sa.JSON(), nullable=True),
    sa.Column('growth_delta', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['academy_player_id'], ['youth_academy_players.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_youth_academy_snapshots_academy_player_id'), 'youth_academy_snapshots', ['academy_player_id'], unique=False)
    op.create_index(op.f('ix_youth_academy_snapshots_season_id'), 'youth_academy_snapshots', ['season_id'], unique=False)
    op.add_column('players', sa.Column('origin_type', sa.Enum('GENERATED', 'ACADEMY', 'DRAFT', 'FREE_MARKET', 'AUTO_FILL', name='origintype'), nullable=False))
    op.add_column('players', sa.Column('academy_team_id', sa.String(length=36), nullable=True))
    op.add_column('players', sa.Column('draft_league_id', sa.String(length=36), nullable=True))
    op.add_column('players', sa.Column('joined_first_team_season', sa.Integer(), nullable=True))
    op.add_column('players', sa.Column('retired_at_season', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_players_academy_team_id'), 'players', ['academy_team_id'], unique=False)
    op.create_index(op.f('ix_players_draft_league_id'), 'players', ['draft_league_id'], unique=False)
    op.create_foreign_key(None, 'players', 'leagues', ['draft_league_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'players', 'teams', ['academy_team_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'players', type_='foreignkey')
    op.drop_constraint(None, 'players', type_='foreignkey')
    op.drop_index(op.f('ix_players_draft_league_id'), table_name='players')
    op.drop_index(op.f('ix_players_academy_team_id'), table_name='players')
    op.drop_column('players', 'retired_at_season')
    op.drop_column('players', 'joined_first_team_season')
    op.drop_column('players', 'draft_league_id')
    op.drop_column('players', 'academy_team_id')
    op.drop_column('players', 'origin_type')
    op.drop_index(op.f('ix_youth_academy_snapshots_season_id'), table_name='youth_academy_snapshots')
    op.drop_index(op.f('ix_youth_academy_snapshots_academy_player_id'), table_name='youth_academy_snapshots')
    op.drop_table('youth_academy_snapshots')
    op.drop_index(op.f('ix_youth_academy_players_team_id'), table_name='youth_academy_players')
    op.drop_index(op.f('ix_youth_academy_players_status'), table_name='youth_academy_players')
    op.drop_index(op.f('ix_youth_academy_players_season_id'), table_name='youth_academy_players')
    op.drop_index(op.f('ix_youth_academy_players_player_id'), table_name='youth_academy_players')
    op.drop_table('youth_academy_players')
    op.drop_index('ix_free_agent_listings_status_season', table_name='free_agent_listings')
    op.drop_index(op.f('ix_free_agent_listings_status'), table_name='free_agent_listings')
    op.drop_index(op.f('ix_free_agent_listings_signed_team_id'), table_name='free_agent_listings')
    op.drop_index(op.f('ix_free_agent_listings_season_id'), table_name='free_agent_listings')
    op.drop_index(op.f('ix_free_agent_listings_player_id'), table_name='free_agent_listings')
    op.drop_index('ix_free_agent_listings_player_active', table_name='free_agent_listings')
    op.drop_index(op.f('ix_free_agent_listings_league_id'), table_name='free_agent_listings')
    op.drop_table('free_agent_listings')
    op.drop_index(op.f('ix_draft_selections_team_id'), table_name='draft_selections')
    op.drop_index(op.f('ix_draft_selections_status'), table_name='draft_selections')
    op.drop_index(op.f('ix_draft_selections_draft_pool_id'), table_name='draft_selections')
    op.drop_table('draft_selections')
    op.drop_index(op.f('ix_draft_preferences_team_id'), table_name='draft_preferences')
    op.drop_index(op.f('ix_draft_preferences_draft_pool_id'), table_name='draft_preferences')
    op.drop_table('draft_preferences')
    op.drop_index(op.f('ix_draft_pool_players_player_id'), table_name='draft_pool_players')
    op.drop_index(op.f('ix_draft_pool_players_draft_pool_id'), table_name='draft_pool_players')
    op.drop_table('draft_pool_players')
    op.drop_index(op.f('ix_draft_pools_season_id'), table_name='draft_pools')
    op.drop_index(op.f('ix_draft_pools_league_id'), table_name='draft_pools')
    op.drop_table('draft_pools')
    # ### end Alembic commands ###
