"""add_team_id_and_season_id_to_mails

Revision ID: 89c483ef864a
Revises: baf768487350
Create Date: 2026-05-28 01:58:13.269519

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89c483ef864a'
down_revision: Union[str, Sequence[str], None] = 'baf768487350'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mails', sa.Column('team_id', sa.String(length=36), nullable=True))
    op.add_column('mails', sa.Column('season_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_mails_season_id'), 'mails', ['season_id'], unique=False)
    op.create_index(op.f('ix_mails_team_id'), 'mails', ['team_id'], unique=False)
    op.create_foreign_key(None, 'mails', 'seasons', ['season_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'mails', 'teams', ['team_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'mails', type_='foreignkey')
    op.drop_constraint(None, 'mails', type_='foreignkey')
    op.drop_index(op.f('ix_mails_team_id'), table_name='mails')
    op.drop_index(op.f('ix_mails_season_id'), table_name='mails')
    op.drop_column('mails', 'season_id')
    op.drop_column('mails', 'team_id')
    # ### end Alembic commands ###
