"""add_player_recent_match_queues

Revision ID: 91a85d00ed63
Revises: 84dbdd46a448
Create Date: 2026-05-29 19:44:51.654369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91a85d00ed63'
down_revision: Union[str, Sequence[str], None] = '84dbdd46a448'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 处理之前部分失败的迁移：先删除可能已存在的列，再统一添加
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    columns = [c['name'] for c in inspector.get_columns('players')]
    if 'recent_ratings' in columns:
        op.drop_column('players', 'recent_ratings')
    if 'recent_minutes' in columns:
        op.drop_column('players', 'recent_minutes')
    op.add_column('players', sa.Column('recent_ratings', sa.JSON(), nullable=True))
    op.add_column('players', sa.Column('recent_minutes', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'recent_minutes')
    op.drop_column('players', 'recent_ratings')
    # ### end Alembic commands ###
