"""add_records_table

Revision ID: 99619842b53f
Revises: 9a1c2d3e4f50
Create Date: 2026-05-27 19:07:18.090112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99619842b53f'
down_revision: Union[str, Sequence[str], None] = '9a1c2d3e4f50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('records',
    sa.Column('scope', sa.Enum('WORLD', 'LEAGUE', 'TEAM', name='recordscope'), nullable=False),
    sa.Column('scope_target_id', sa.String(length=36), nullable=True, comment='WORLD=null, LEAGUE=league_id, TEAM=team_id'),
    sa.Column('category', sa.Enum('TEAM', 'PLAYER', 'MATCH', name='recordcategory'), nullable=False),
    sa.Column('record_type', sa.Enum('CAREER_GOALS', 'CAREER_ASSISTS', 'CAREER_APPEARANCES', 'CAREER_YELLOW_CARDS', 'CAREER_RED_CARDS', 'CAREER_RATING', 'SEASON_GOALS', 'SEASON_ASSISTS', 'SEASON_RATING', 'MATCH_GOALS', 'MATCH_ASSISTS', 'FASTEST_GOAL', 'YOUNGEST_SCORER', 'OLDEST_SCORER', 'HAT_TRICKS', 'SCORING_STREAK', 'ASSIST_STREAK', 'SEASON_TEAM_GOALS', 'SEASON_TEAM_GOALS_AGAINST', 'SEASON_TEAM_POINTS', 'SEASON_TEAM_WINS', 'SEASON_CLEAN_SHEETS', 'BIGGEST_WIN_MARGIN', 'BIGGEST_DEFEAT_MARGIN', 'MOST_GOALS_IN_MATCH', 'LONGEST_WIN_STREAK', 'LONGEST_UNBEATEN', 'LONGEST_LOSING_STREAK', name='recordtype'), nullable=False),
    sa.Column('holder_player_id', sa.String(length=36), nullable=True),
    sa.Column('holder_team_id', sa.String(length=36), nullable=True),
    sa.Column('record_value', sa.String(length=100), nullable=False, comment="展示值，如 '34球', '11秒'"),
    sa.Column('record_value_numeric', sa.DECIMAL(precision=12, scale=2), nullable=False, comment='用于排序比较的数值，统一越大越好'),
    sa.Column('season_id', sa.String(length=36), nullable=True),
    sa.Column('fixture_id', sa.String(length=36), nullable=True),
    sa.Column('match_date', sa.Date(), nullable=True),
    sa.Column('context', sa.JSON(), nullable=False, comment='额外信息，如 streak 起止日期等'),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['fixture_id'], ['fixtures.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['holder_player_id'], ['players.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['holder_team_id'], ['teams.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scope', 'scope_target_id', 'record_type', name='uix_record_scope_type')
    )
    op.create_index(op.f('ix_records_category'), 'records', ['category'], unique=False)
    op.create_index(op.f('ix_records_holder_player_id'), 'records', ['holder_player_id'], unique=False)
    op.create_index(op.f('ix_records_holder_team_id'), 'records', ['holder_team_id'], unique=False)
    op.create_index(op.f('ix_records_record_type'), 'records', ['record_type'], unique=False)
    op.create_index(op.f('ix_records_record_value_numeric'), 'records', ['record_value_numeric'], unique=False)
    op.create_index(op.f('ix_records_scope'), 'records', ['scope'], unique=False)
    op.create_index(op.f('ix_records_scope_target_id'), 'records', ['scope_target_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_records_scope_target_id'), table_name='records')
    op.drop_index(op.f('ix_records_scope'), table_name='records')
    op.drop_index(op.f('ix_records_record_value_numeric'), table_name='records')
    op.drop_index(op.f('ix_records_record_type'), table_name='records')
    op.drop_index(op.f('ix_records_holder_team_id'), table_name='records')
    op.drop_index(op.f('ix_records_holder_player_id'), table_name='records')
    op.drop_index(op.f('ix_records_category'), table_name='records')
    op.drop_table('records')
    # ### end Alembic commands ###
