"""add_player_short_description

Revision ID: 9bf1b5aaa29e
Revises: 3ce123a33e9e
Create Date: 2026-06-16 13:42:22.005410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9bf1b5aaa29e'
down_revision: Union[str, Sequence[str], None] = '3ce123a33e9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('short_description', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'short_description')
    # ### end Alembic commands ###
