"""add_finance_tables

Revision ID: af99f8ece916
Revises: b038b425d9cc
Create Date: 2026-05-28 00:39:35.323287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af99f8ece916'
down_revision: Union[str, Sequence[str], None] = 'b038b425d9cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('finance_transactions',
    sa.Column('team_id', sa.String(length=36), nullable=False),
    sa.Column('season_id', sa.String(length=36), nullable=False),
    sa.Column('event_queue_id', sa.Integer(), nullable=True),
    sa.Column('source_type', sa.Enum('BROADCAST', 'SPONSOR', 'MATCH_BONUS', 'CUP_PRIZE', 'LEAGUE_PRIZE', 'WAGE', 'TRANSFER', 'YOUTH', 'PENALTY', 'MANUAL_ADJUSTMENT', name='transactionsourcetype'), nullable=False),
    sa.Column('direction', sa.Enum('INCOME', 'EXPENSE', name='transactiondirection'), nullable=False),
    sa.Column('amount', sa.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('balance_after', sa.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['event_queue_id'], ['event_queues.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_finance_transactions_season_id'), 'finance_transactions', ['season_id'], unique=False)
    op.create_index(op.f('ix_finance_transactions_team_id'), 'finance_transactions', ['team_id'], unique=False)
    op.create_table('team_season_finances',
    sa.Column('team_id', sa.String(length=36), nullable=False),
    sa.Column('season_id', sa.String(length=36), nullable=False),
    sa.Column('opening_balance', sa.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('current_balance', sa.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('projected_income', sa.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('projected_expense', sa.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('locked_budget_total', sa.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('transfer_budget', sa.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('youth_budget', sa.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('wage_budget', sa.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('reserve_budget', sa.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('wage_cap', sa.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('wage_bill', sa.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('financial_health', sa.Enum('A', 'B', 'C', 'D', name='financialhealth'), nullable=False),
    sa.Column('overspend_level', sa.Enum('NONE', 'WARNING', 'RESTRICTED', 'CRISIS', name='overspendlevel'), nullable=False),
    sa.Column('budget_locked_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'season_id', name='uix_team_season_finance')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('team_season_finances')
    op.drop_index(op.f('ix_finance_transactions_team_id'), table_name='finance_transactions')
    op.drop_index(op.f('ix_finance_transactions_season_id'), table_name='finance_transactions')
    op.drop_table('finance_transactions')
    # ### end Alembic commands ###
