"""add_mails_table

Revision ID: b038b425d9cc
Revises: 99619842b53f
Create Date: 2026-05-28 00:17:03.546642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b038b425d9cc'
down_revision: Union[str, Sequence[str], None] = '99619842b53f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mails',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('category', sa.Enum('MATCH_PREVIEW', 'MATCH_RESULT', 'SPONSOR', 'TRANSFER', 'FINANCE', 'SYSTEM', name='mailcategory'), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'NORMAL', 'HIGH', 'URGENT', name='mailpriority'), nullable=False),
    sa.Column('sender_name', sa.String(length=100), nullable=False),
    sa.Column('sender_avatar_url', sa.String(length=255), nullable=True),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('related_id', sa.String(length=36), nullable=True),
    sa.Column('related_type', sa.String(length=50), nullable=True),
    sa.Column('related_url', sa.String(length=255), nullable=True),
    sa.Column('has_action', sa.Boolean(), nullable=False),
    sa.Column('action_taken', sa.Boolean(), nullable=False),
    sa.Column('action_label', sa.String(length=50), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_mails_created', 'mails', ['created_at'], unique=False)
    op.create_index('ix_mails_user_category', 'mails', ['user_id', 'category'], unique=False)
    op.create_index(op.f('ix_mails_user_id'), 'mails', ['user_id'], unique=False)
    op.create_index('ix_mails_user_read', 'mails', ['user_id', 'is_read'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_mails_user_read', table_name='mails')
    op.drop_index(op.f('ix_mails_user_id'), table_name='mails')
    op.drop_index('ix_mails_user_category', table_name='mails')
    op.drop_index('ix_mails_created', table_name='mails')
    op.drop_table('mails')
    # ### end Alembic commands ###
