"""make_player_weight_foot_nullable

Revision ID: b6feb46a21d3
Revises: cea321ffd6da
Create Date: 2026-06-16 20:00:11.944293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b6feb46a21d3'
down_revision: Union[str, Sequence[str], None] = 'cea321ffd6da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('players', 'preferred_foot',
               existing_type=mysql.ENUM('LEFT', 'RIGHT', 'BOTH', collation='utf8mb4_unicode_ci'),
               nullable=True)
    op.alter_column('players', 'weight',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('players', 'weight',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('players', 'preferred_foot',
               existing_type=mysql.ENUM('LEFT', 'RIGHT', 'BOTH', collation='utf8mb4_unicode_ci'),
               nullable=False)
    # ### end Alembic commands ###
