"""add_budget_and_sponsor_tables

Revision ID: baf768487350
Revises: af99f8ece916
Create Date: 2026-05-28 01:27:30.069525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'baf768487350'
down_revision: Union[str, Sequence[str], None] = 'af99f8ece916'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sponsor_contracts',
    sa.Column('team_id', sa.String(length=36), nullable=False),
    sa.Column('season_id', sa.String(length=36), nullable=False),
    sa.Column('policy', sa.Enum('STABLE', 'PERFORMANCE', name='sponsorpolicy'), nullable=False),
    sa.Column('base_amount', sa.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('win_bonus', sa.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('draw_bonus', sa.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('goal_bonus', sa.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('max_bonus', sa.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('health_modifier_pct', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'COMPLETED', name='sponsorcontractstatus'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sponsor_contracts_season_id'), 'sponsor_contracts', ['season_id'], unique=False)
    op.create_index(op.f('ix_sponsor_contracts_team_id'), 'sponsor_contracts', ['team_id'], unique=False)
    op.create_table('team_budget_plans',
    sa.Column('team_id', sa.String(length=36), nullable=False),
    sa.Column('target_season_id', sa.String(length=36), nullable=False),
    sa.Column('policy', sa.Enum('BALANCED', 'YOUTH_FOCUS', 'TRANSFER_PUSH', 'WAGE_CONTROL', 'CUSTOM', name='budgetpolicy'), nullable=False),
    sa.Column('transfer_pct', sa.Integer(), nullable=False),
    sa.Column('youth_pct', sa.Integer(), nullable=False),
    sa.Column('wage_pct', sa.Integer(), nullable=False),
    sa.Column('reserve_pct', sa.Integer(), nullable=False),
    sa.Column('is_player_confirmed', sa.Boolean(), nullable=False),
    sa.Column('locked_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['target_season_id'], ['seasons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'target_season_id', name='uix_team_budget_plan')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('team_budget_plans')
    op.drop_index(op.f('ix_sponsor_contracts_team_id'), table_name='sponsor_contracts')
    op.drop_index(op.f('ix_sponsor_contracts_season_id'), table_name='sponsor_contracts')
    op.drop_table('sponsor_contracts')
    # ### end Alembic commands ###
