"""drop_player_weight_preferred_foot

Revision ID: bfcccf8c00dc
Revises: b6feb46a21d3
Create Date: 2026-06-16 20:40:40.899744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'bfcccf8c00dc'
down_revision: Union[str, Sequence[str], None] = 'b6feb46a21d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'preferred_foot')
    op.drop_column('players', 'weight')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('weight', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('players', sa.Column('preferred_foot', mysql.ENUM('LEFT', 'RIGHT', 'BOTH', charset='utf8mb4', collation='utf8mb4_unicode_ci'), nullable=True))
    # ### end Alembic commands ###
