"""add_injury_system_v2_fields

Revision ID: cbde578eaaa0
Revises: 62b4d4534265
Create Date: 2026-06-05 14:19:55.213413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cbde578eaaa0'
down_revision: Union[str, Sequence[str], None] = '62b4d4534265'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('players', sa.Column('body_wear', sa.JSON(), nullable=True))
    op.add_column('players', sa.Column('traits', sa.JSON(), nullable=True))
    op.add_column('players', sa.Column('current_injury', sa.JSON(), nullable=True))
    op.add_column('players', sa.Column('injury_history', sa.JSON(), nullable=True))
    op.execute("UPDATE players SET body_wear = JSON_OBJECT() WHERE body_wear IS NULL")
    op.execute("UPDATE players SET traits = JSON_ARRAY() WHERE traits IS NULL")
    op.execute("UPDATE players SET injury_history = JSON_ARRAY() WHERE injury_history IS NULL")
    op.alter_column('players', 'body_wear', existing_type=sa.JSON(), nullable=False)
    op.alter_column('players', 'traits', existing_type=sa.JSON(), nullable=False)
    op.alter_column('players', 'injury_history', existing_type=sa.JSON(), nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'injury_history')
    op.drop_column('players', 'current_injury')
    op.drop_column('players', 'traits')
    op.drop_column('players', 'body_wear')
    # ### end Alembic commands ###
