"""add_unique_index_to_player_feedback

Revision ID: cea321ffd6da
Revises: 9bf1b5aaa29e
Create Date: 2026-06-16 19:42:38.783113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cea321ffd6da'
down_revision: Union[str, Sequence[str], None] = '9bf1b5aaa29e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uix_player_feedback_player_day', 'player_feedbacks', ['player_id', 'day_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_player_feedback_player_day', 'player_feedbacks', type_='unique')
    # ### end Alembic commands ###
