"""initial_schema

Revision ID: d33acbde10b5
Revises: 
Create Date: 2026-04-10 00:29:56.973627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd33acbde10b5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('league_systems',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('max_teams_per_league', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('seasons',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('UPCOMING', 'ONGOING', 'COMPLETED', name='seasonstatus'), nullable=False),
    sa.Column('transfer_window_open', sa.Boolean(), nullable=False),
    sa.Column('transfer_window_start', sa.DateTime(), nullable=True),
    sa.Column('transfer_window_end', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seasons_status'), 'seasons', ['status'], unique=False)
    op.create_table('users',
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('nickname', sa.String(length=50), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('is_ai', sa.Boolean(), nullable=False),
    sa.Column('is_vip', sa.Boolean(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('experience', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'BANNED', name='userstatus'), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_is_ai'), 'users', ['is_ai'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('leagues',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('system_id', sa.String(length=36), nullable=False),
    sa.Column('max_teams', sa.Integer(), nullable=False),
    sa.Column('promotion_spots', sa.Integer(), nullable=False),
    sa.Column('relegation_spots', sa.Integer(), nullable=False),
    sa.Column('has_promotion_playoff', sa.Boolean(), nullable=False),
    sa.Column('has_relegation_playoff', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['system_id'], ['league_systems.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leagues_level'), 'leagues', ['level'], unique=False)
    op.create_index(op.f('ix_leagues_system_id'), 'leagues', ['system_id'], unique=False)
    op.create_table('teams',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('short_name', sa.String(length=10), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('stadium', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=50), nullable=True),
    sa.Column('founded_year', sa.Integer(), nullable=True),
    sa.Column('reputation', sa.Integer(), nullable=False),
    sa.Column('overall_rating', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'SUSPENDED', name='teamstatus'), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('current_league_id', sa.String(length=36), nullable=True),
    sa.Column('current_season_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['current_league_id'], ['leagues.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['current_season_id'], ['seasons.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_teams_current_league_id'), 'teams', ['current_league_id'], unique=False)
    op.create_table('league_standings',
    sa.Column('league_id', sa.String(length=36), nullable=False),
    sa.Column('season_id', sa.String(length=36), nullable=False),
    sa.Column('team_id', sa.String(length=36), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('played', sa.Integer(), nullable=False),
    sa.Column('won', sa.Integer(), nullable=False),
    sa.Column('drawn', sa.Integer(), nullable=False),
    sa.Column('lost', sa.Integer(), nullable=False),
    sa.Column('goals_for', sa.Integer(), nullable=False),
    sa.Column('goals_against', sa.Integer(), nullable=False),
    sa.Column('goal_difference', sa.Integer(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('form', sa.String(length=10), nullable=True),
    sa.Column('is_promotion_zone', sa.Boolean(), nullable=False),
    sa.Column('is_relegation_zone', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id')
    )
    op.create_index(op.f('ix_league_standings_league_id'), 'league_standings', ['league_id'], unique=False)
    op.create_index(op.f('ix_league_standings_position'), 'league_standings', ['position'], unique=False)
    op.create_index(op.f('ix_league_standings_season_id'), 'league_standings', ['season_id'], unique=False)
    op.create_table('players',
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('nationality', sa.String(length=50), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('preferred_foot', sa.Enum('LEFT', 'RIGHT', 'BOTH', name='playerfoot'), nullable=False),
    sa.Column('primary_position', sa.Enum('GK', 'CB', 'LB', 'RB', 'LWB', 'RWB', 'CDM', 'CM', 'CAM', 'LM', 'RM', 'LW', 'RW', 'LF', 'RF', 'ST', 'CF', name='playerposition'), nullable=False),
    sa.Column('secondary_position', sa.Enum('GK', 'CB', 'LB', 'RB', 'LWB', 'RWB', 'CDM', 'CM', 'CAM', 'LM', 'RM', 'LW', 'RW', 'LF', 'RF', 'ST', 'CF', name='playerposition'), nullable=True),
    sa.Column('shooting', sa.Integer(), nullable=False),
    sa.Column('finishing', sa.Integer(), nullable=False),
    sa.Column('long_shots', sa.Integer(), nullable=False),
    sa.Column('passing', sa.Integer(), nullable=False),
    sa.Column('vision', sa.Integer(), nullable=False),
    sa.Column('crossing', sa.Integer(), nullable=False),
    sa.Column('dribbling', sa.Integer(), nullable=False),
    sa.Column('ball_control', sa.Integer(), nullable=False),
    sa.Column('defending', sa.Integer(), nullable=False),
    sa.Column('tackling', sa.Integer(), nullable=False),
    sa.Column('marking', sa.Integer(), nullable=False),
    sa.Column('pace', sa.Integer(), nullable=False),
    sa.Column('acceleration', sa.Integer(), nullable=False),
    sa.Column('strength', sa.Integer(), nullable=False),
    sa.Column('stamina', sa.Integer(), nullable=False),
    sa.Column('diving', sa.Integer(), nullable=False),
    sa.Column('handling', sa.Integer(), nullable=False),
    sa.Column('kicking', sa.Integer(), nullable=False),
    sa.Column('reflexes', sa.Integer(), nullable=False),
    sa.Column('positioning', sa.Integer(), nullable=False),
    sa.Column('aggression', sa.Integer(), nullable=False),
    sa.Column('composure', sa.Integer(), nullable=False),
    sa.Column('work_rate', sa.Integer(), nullable=False),
    sa.Column('overall_rating', sa.Integer(), nullable=False),
    sa.Column('potential', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INJURED', 'SUSPENDED', 'RETIRED', name='playerstatus'), nullable=False),
    sa.Column('fitness', sa.Integer(), nullable=False),
    sa.Column('morale', sa.Integer(), nullable=False),
    sa.Column('form', sa.Integer(), nullable=False),
    sa.Column('wage', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('contract_end', sa.Date(), nullable=True),
    sa.Column('release_clause', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('squad_role', sa.Enum('KEY_PLAYER', 'FIRST_TEAM', 'ROTATION', 'BACKUP', 'HOT_PROSPECT', 'YOUNGSTER', 'NOT_NEEDED', name='squadrole'), nullable=False),
    sa.Column('market_value', sa.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('matches_played', sa.Integer(), nullable=False),
    sa.Column('goals', sa.Integer(), nullable=False),
    sa.Column('assists', sa.Integer(), nullable=False),
    sa.Column('yellow_cards', sa.Integer(), nullable=False),
    sa.Column('red_cards', sa.Integer(), nullable=False),
    sa.Column('average_rating', sa.DECIMAL(precision=3, scale=1), nullable=False),
    sa.Column('minutes_played', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_players_team_id'), 'players', ['team_id'], unique=False)
    op.create_table('team_finances',
    sa.Column('team_id', sa.String(length=36), nullable=False),
    sa.Column('balance', sa.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('weekly_wage_bill', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('stadium_capacity', sa.Integer(), nullable=False),
    sa.Column('ticket_price', sa.DECIMAL(precision=8, scale=2), nullable=False),
    sa.Column('weekly_sponsor_income', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('weekly_ticket_income', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('transfer_budget', sa.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('wage_budget', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('team_id', 'id')
    )
    op.create_table('matches',
    sa.Column('season_id', sa.String(length=36), nullable=False),
    sa.Column('league_id', sa.String(length=36), nullable=False),
    sa.Column('matchday', sa.Integer(), nullable=False),
    sa.Column('home_team_id', sa.String(length=36), nullable=False),
    sa.Column('away_team_id', sa.String(length=36), nullable=False),
    sa.Column('home_score', sa.Integer(), nullable=True),
    sa.Column('away_score', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('SCHEDULED', 'ONGOING', 'FINISHED', 'POSTPONED', 'CANCELLED', name='matchstatus'), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('home_possession', sa.Integer(), nullable=True),
    sa.Column('away_possession', sa.Integer(), nullable=True),
    sa.Column('home_shots', sa.Integer(), nullable=True),
    sa.Column('away_shots', sa.Integer(), nullable=True),
    sa.Column('home_shots_on_target', sa.Integer(), nullable=True),
    sa.Column('away_shots_on_target', sa.Integer(), nullable=True),
    sa.Column('mvp_player_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['away_team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['home_team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['mvp_player_id'], ['players.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_matches_away_team_id'), 'matches', ['away_team_id'], unique=False)
    op.create_index(op.f('ix_matches_home_team_id'), 'matches', ['home_team_id'], unique=False)
    op.create_index(op.f('ix_matches_league_id'), 'matches', ['league_id'], unique=False)
    op.create_index(op.f('ix_matches_matchday'), 'matches', ['matchday'], unique=False)
    op.create_index(op.f('ix_matches_scheduled_at'), 'matches', ['scheduled_at'], unique=False)
    op.create_index(op.f('ix_matches_season_id'), 'matches', ['season_id'], unique=False)
    op.create_index(op.f('ix_matches_status'), 'matches', ['status'], unique=False)
    op.drop_table('health_check')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('health_check',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('message', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_index(op.f('ix_matches_status'), table_name='matches')
    op.drop_index(op.f('ix_matches_season_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_scheduled_at'), table_name='matches')
    op.drop_index(op.f('ix_matches_matchday'), table_name='matches')
    op.drop_index(op.f('ix_matches_league_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_home_team_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_away_team_id'), table_name='matches')
    op.drop_table('matches')
    op.drop_table('team_finances')
    op.drop_index(op.f('ix_players_team_id'), table_name='players')
    op.drop_table('players')
    op.drop_index(op.f('ix_league_standings_season_id'), table_name='league_standings')
    op.drop_index(op.f('ix_league_standings_position'), table_name='league_standings')
    op.drop_index(op.f('ix_league_standings_league_id'), table_name='league_standings')
    op.drop_table('league_standings')
    op.drop_index(op.f('ix_teams_current_league_id'), table_name='teams')
    op.drop_table('teams')
    op.drop_index(op.f('ix_leagues_system_id'), table_name='leagues')
    op.drop_index(op.f('ix_leagues_level'), table_name='leagues')
    op.drop_table('leagues')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_is_ai'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_seasons_status'), table_name='seasons')
    op.drop_table('seasons')
    op.drop_table('league_systems')
    # ### end Alembic commands ###
