"""add_event_queue

Revision ID: e0d9f135233e
Revises: 58f5f5484083
Create Date: 2026-05-04 23:49:35.063107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0d9f135233e'
down_revision: Union[str, Sequence[str], None] = '58f5f5484083'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_queues',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('error_msg', sa.String(length=500), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_queues_event_type'), 'event_queues', ['event_type'], unique=False)
    op.create_index(op.f('ix_event_queues_scheduled_at'), 'event_queues', ['scheduled_at'], unique=False)
    op.create_index(op.f('ix_event_queues_status'), 'event_queues', ['status'], unique=False)
    op.create_index('ix_event_queues_status_scheduled', 'event_queues', ['status', 'scheduled_at'], unique=False)
    op.add_column('players', sa.Column('rus', sa.Integer(), nullable=False))
    op.add_column('players', sa.Column('dec', sa.Integer(), nullable=False))
    op.add_column('players', sa.Column('fk', sa.Integer(), nullable=False))
    op.add_column('players', sa.Column('pk', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'pk')
    op.drop_column('players', 'fk')
    op.drop_column('players', 'dec')
    op.drop_column('players', 'rus')
    op.drop_index('ix_event_queues_status_scheduled', table_name='event_queues')
    op.drop_index(op.f('ix_event_queues_status'), table_name='event_queues')
    op.drop_index(op.f('ix_event_queues_scheduled_at'), table_name='event_queues')
    op.drop_index(op.f('ix_event_queues_event_type'), table_name='event_queues')
    op.drop_table('event_queues')
    # ### end Alembic commands ###
