"""add_player_state_fields_for_phase5

Revision ID: e15512f5daa9
Revises: 89c483ef864a
Create Date: 2026-05-28 02:15:58.997532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e15512f5daa9'
down_revision: Union[str, Sequence[str], None] = '89c483ef864a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('recommended_wage', sa.DECIMAL(precision=12, scale=2), nullable=True))
    op.add_column('players', sa.Column('wage_ratio', sa.DECIMAL(precision=5, scale=2), nullable=True))
    op.add_column('players', sa.Column('wage_satisfaction', sa.Integer(), nullable=False))
    op.add_column('players', sa.Column('state_score', sa.Integer(), nullable=False))
    op.add_column('players', sa.Column('state_updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'state_updated_at')
    op.drop_column('players', 'state_score')
    op.drop_column('players', 'wage_satisfaction')
    op.drop_column('players', 'wage_ratio')
    op.drop_column('players', 'recommended_wage')
    # ### end Alembic commands ###
